module.exports = {
   /**
    * Gets locale based on HTML lang attribute
    * @returns {object} {code, lang, region}
    */
   getHTMLLocale = () => {
      const code = document.querySelector('html').getAttribute('lang')

      return code
         ? locale = {
            code: code.substr(0, 2),
            ...LOCALES[code]
         }
         : '⚠ - No lang attribute'
   }
}

const LOCALES = {
   af_NA: { lang: "Afrikaans", region: "Namibia" },
   af_ZA: { lang: "Afrikaans", region: "South Africa" },
   af: { lang: "Afrikaans" },
   ak_GH: { lang: "Akan", region: "Ghana" },
   ak: { lang: "Akan" },
   sq_AL: { lang: "Albanian", region: "Albania" },
   sq: { lang: "Albanian" },
   am_ET: { lang: "Amharic", region: "Ethiopia" },
   am: { lang: "Amharic" },
   ar_DZ: { lang: "Arabic", region: "Algeria" },
   ar_BH: { lang: "Arabic", region: "Bahrain" },
   ar_EG: { lang: "Arabic", region: "Egypt" },
   ar_IQ: { lang: "Arabic", region: "Iraq" },
   ar_JO: { lang: "Arabic", region: "Jordan" },
   ar_KW: { lang: "Arabic", region: "Kuwait" },
   ar_LB: { lang: "Arabic", region: "Lebanon" },
   ar_LY: { lang: "Arabic", region: "Libya" },
   ar_MA: { lang: "Arabic", region: "Morocco" },
   ar_OM: { lang: "Arabic", region: "Oman" },
   ar_QA: { lang: "Arabic", region: "Qatar" },
   ar_SA: { lang: "Arabic", region: "Saudi Arabia" },
   ar_SD: { lang: "Arabic", region: "Sudan" },
   ar_SY: { lang: "Arabic", region: "Syria" },
   ar_TN: { lang: "Arabic", region: "Tunisia" },
   ar_AE: { lang: "Arabic", region: "United Arab Emirates" },
   ar_YE: { lang: "Arabic", region: "Yemen" },
   ar: { lang: "Arabic" },
   hy_AM: { lang: "Armenian", region: "Armenia" },
   hy: { lang: "Armenian" },
   as_IN: { lang: "Assamese", region: "India" },
   as: { lang: "Assamese" },
   asa_TZ: { lang: "Asu", region: "Tanzania" },
   asa: { lang: "Asu" },
   az_Cyrl: { lang: "Azerbaijani", region: "Cyrillic" },
   az_Cyrl_AZ: { lang: "Azerbaijani", region: "Cyrillic, Azerbaijan" },
   az_Latn: { lang: "Azerbaijani", region: "Latin" },
   az_Latn_AZ: { lang: "Azerbaijani", region: "Latin, Azerbaijan" },
   az: { lang: "Azerbaijani" },
   bm_ML: { lang: "Bambara", region: "Mali" },
   bm: { lang: "Bambara" },
   eu_ES: { lang: "Basque", region: "Spain" },
   eu: { lang: "Basque" },
   be_BY: { lang: "Belarusian", region: "Belarus" },
   be: { lang: "Belarusian" },
   bem_ZM: { lang: "Bemba", region: "Zambia" },
   bem: { lang: "Bemba" },
   bez_TZ: { lang: "Bena", region: "Tanzania" },
   bez: { lang: "Bena" },
   bn_BD: { lang: "Bengali", region: "Bangladesh" },
   bn_IN: { lang: "Bengali", region: "India" },
   bn: { lang: "Bengali" },
   bs_BA: { lang: "Bosnian", region: "Bosnia and Herzegovina" },
   bs: { lang: "Bosnian" },
   bg_BG: { lang: "Bulgarian", region: "Bulgaria" },
   bg: { lang: "Bulgarian" },
   my_MM: { lang: "Burmese", region: "Myanmar (Burma)" },
   my: { lang: "Burmese" },
   yue_Hant_HK: { lang: "Cantonese", region: "Traditional, Hong Kong SAR China" },
   ca_ES: { lang: "Catalan", region: "Spain" },
   ca: { lang: "Catalan" },
   tzm_Latn: { lang: "Central Morocco Tamazight", region: "Latin" },
   tzm_Latn_MA: { lang: "Central Morocco Tamazight", region: "Latin, Morocco" },
   tzm: { lang: "Central Morocco Tamazight" },
   chr_US: { lang: "Cherokee", region: "United States" },
   chr: { lang: "Cherokee" },
   cgg_UG: { lang: "Chiga", region: "Uganda" },
   cgg: { lang: "Chiga" },
   zh_Hans: { lang: "Chinese", region: "Simplified Han" },
   zh_Hans_CN: { lang: "Chinese", region: "Simplified Han, China" },
   zh_Hans_HK: { lang: "Chinese", region: "Simplified Han, Hong Kong SAR China" },
   zh_Hans_MO: { lang: "Chinese", region: "Simplified Han, Macau SAR China" },
   zh_Hans_SG: { lang: "Chinese", region: "Simplified Han, Singapore" },
   zh_Hant: { lang: "Chinese", region: "Traditional Han" },
   zh_Hant_HK: { lang: "Chinese", region: "Traditional Han, Hong Kong SAR China" },
   zh_Hant_MO: { lang: "Chinese", region: "Traditional Han, Macau SAR China" },
   zh_Hant_TW: { lang: "Chinese", region: "Traditional Han, Taiwan" },
   zh: { lang: "Chinese" },
   kw_GB: { lang: "Cornish", region: "United Kingdom" },
   kw: { lang: "Cornish" },
   hr_HR: { lang: "Croatian", region: "Croatia" },
   hr: { lang: "Croatian" },
   cs_CZ: { lang: "Czech", region: "Czech Republic" },
   cs: { lang: "Czech" },
   da_DK: { lang: "Danish", region: "Denmark" },
   da: { lang: "Danish" },
   nl_BE: { lang: "Dutch", region: "Belgium" },
   nl_NL: { lang: "Dutch", region: "Netherlands" },
   nl: { lang: "Dutch" },
   ebu_KE: { lang: "Embu", region: "Kenya" },
   ebu: { lang: "Embu" },
   en_AS: { lang: "English", region: "American Samoa" },
   en_AU: { lang: "English", region: "Australia" },
   en_BE: { lang: "English", region: "Belgium" },
   en_BZ: { lang: "English", region: "Belize" },
   en_BW: { lang: "English", region: "Botswana" },
   en_CA: { lang: "English", region: "Canada" },
   en_GU: { lang: "English", region: "Guam" },
   en_HK: { lang: "English", region: "Hong Kong SAR China" },
   en_IN: { lang: "English", region: "India" },
   en_IE: { lang: "English", region: "Ireland" },
   en_IL: { lang: "English", region: "Israel" },
   en_JM: { lang: "English", region: "Jamaica" },
   en_MT: { lang: "English", region: "Malta" },
   en_MH: { lang: "English", region: "Marshall Islands" },
   en_MU: { lang: "English", region: "Mauritius" },
   en_NA: { lang: "English", region: "Namibia" },
   en_NZ: { lang: "English", region: "New Zealand" },
   en_MP: { lang: "English", region: "Northern Mariana Islands" },
   en_PK: { lang: "English", region: "Pakistan" },
   en_PH: { lang: "English", region: "Philippines" },
   en_SG: { lang: "English", region: "Singapore" },
   en_ZA: { lang: "English", region: "South Africa" },
   en_TT: { lang: "English", region: "Trinidad and Tobago" },
   en_UM: { lang: "English", region: "U.S. Minor Outlying Islands" },
   en_VI: { lang: "English", region: "U.S. Virgin Islands" },
   en_GB: { lang: "English", region: "United Kingdom" },
   en_US: { lang: "English", region: "United States" },
   en_ZW: { lang: "English", region: "Zimbabwe" },
   en: { lang: "English" },
   eo: { lang: "Esperanto" },
   et_EE: { lang: "Estonian", region: "Estonia" },
   et: { lang: "Estonian" },
   ee_GH: { lang: "Ewe", region: "Ghana" },
   ee_TG: { lang: "Ewe", region: "Togo" },
   ee: { lang: "Ewe" },
   fo_FO: { lang: "Faroese", region: "Faroe Islands" },
   fo: { lang: "Faroese" },
   fil_PH: { lang: "Filipino", region: "Philippines" },
   fil: { lang: "Filipino" },
   fi_FI: { lang: "Finnish", region: "Finland" },
   fi: { lang: "Finnish" },
   fr_BE: { lang: "French", region: "Belgium" },
   fr_BJ: { lang: "French", region: "Benin" },
   fr_BF: { lang: "French", region: "Burkina Faso" },
   fr_BI: { lang: "French", region: "Burundi" },
   fr_CM: { lang: "French", region: "Cameroon" },
   fr_CA: { lang: "French", region: "Canada" },
   fr_CF: { lang: "French", region: "Central African Republic" },
   fr_TD: { lang: "French", region: "Chad" },
   fr_KM: { lang: "French", region: "Comoros" },
   fr_CG: { lang: "French", region: "Congo - Brazzaville" },
   fr_CD: { lang: "French", region: "Congo - Kinshasa" },
   fr_CI: { lang: "French", region: "Côte d’Ivoire" },
   fr_DJ: { lang: "French", region: "Djibouti" },
   fr_GQ: { lang: "French", region: "Equatorial Guinea" },
   fr_FR: { lang: "French", region: "France" },
   fr_GA: { lang: "French", region: "Gabon" },
   fr_GP: { lang: "French", region: "Guadeloupe" },
   fr_GN: { lang: "French", region: "Guinea" },
   fr_LU: { lang: "French", region: "Luxembourg" },
   fr_MG: { lang: "French", region: "Madagascar" },
   fr_ML: { lang: "French", region: "Mali" },
   fr_MQ: { lang: "French", region: "Martinique" },
   fr_MC: { lang: "French", region: "Monaco" },
   fr_NE: { lang: "French", region: "Niger" },
   fr_RW: { lang: "French", region: "Rwanda" },
   fr_RE: { lang: "French", region: "Réunion" },
   fr_BL: { lang: "French", region: "Saint Barthélemy" },
   fr_MF: { lang: "French", region: "Saint Martin" },
   fr_SN: { lang: "French", region: "Senegal" },
   fr_CH: { lang: "French", region: "Switzerland" },
   fr_TG: { lang: "French", region: "Togo" },
   fr: { lang: "French" },
   ff_SN: { lang: "Fulah", region: "Senegal" },
   ff: { lang: "Fulah" },
   gl_ES: { lang: "Galician", region: "Spain" },
   gl: { lang: "Galician" },
   lg_UG: { lang: "Ganda", region: "Uganda" },
   lg: { lang: "Ganda" },
   ka_GE: { lang: "Georgian", region: "Georgia" },
   ka: { lang: "Georgian" },
   de_AT: { lang: "German", region: "Austria" },
   de_BE: { lang: "German", region: "Belgium" },
   de_DE: { lang: "German", region: "Germany" },
   de_LI: { lang: "German", region: "Liechtenstein" },
   de_LU: { lang: "German", region: "Luxembourg" },
   de_CH: { lang: "German", region: "Switzerland" },
   de: { lang: "German" },
   el_CY: { lang: "Greek", region: "Cyprus" },
   el_GR: { lang: "Greek", region: "Greece" },
   el: { lang: "Greek" },
   gu_IN: { lang: "Gujarati", region: "India" },
   gu: { lang: "Gujarati" },
   guz_KE: { lang: "Gusii", region: "Kenya" },
   guz: { lang: "Gusii" },
   ha_Latn: { lang: "Hausa", region: "Latin" },
   ha_Latn_GH: { lang: "Hausa", region: "Latin, Ghana" },
   ha_Latn_NE: { lang: "Hausa", region: "Latin, Niger" },
   ha_Latn_NG: { lang: "Hausa", region: "Latin, Nigeria" },
   ha: { lang: "Hausa" },
   haw_US: { lang: "Hawaiian", region: "United States" },
   haw: { lang: "Hawaiian" },
   he_IL: { lang: "Hebrew", region: "Israel" },
   he: { lang: "Hebrew" },
   hi_IN: { lang: "Hindi", region: "India" },
   hi: { lang: "Hindi" },
   hu_HU: { lang: "Hungarian", region: "Hungary" },
   hu: { lang: "Hungarian" },
   is_IS: { lang: "Icelandic", region: "Iceland" },
   is: { lang: "Icelandic" },
   ig_NG: { lang: "Igbo", region: "Nigeria" },
   ig: { lang: "Igbo" },
   id_ID: { lang: "Indonesian", region: "Indonesia" },
   id: { lang: "Indonesian" },
   ga_IE: { lang: "Irish", region: "Ireland" },
   ga: { lang: "Irish" },
   it_IT: { lang: "Italian", region: "Italy" },
   it_CH: { lang: "Italian", region: "Switzerland" },
   it: { lang: "Italian" },
   ja_JP: { lang: "Japanese", region: "Japan" },
   ja: { lang: "Japanese" },
   kea_CV: { lang: "Kabuverdianu", region: "Cape Verde" },
   kea: { lang: "Kabuverdianu" },
   kab_DZ: { lang: "Kabyle", region: "Algeria" },
   kab: { lang: "Kabyle" },
   kl_GL: { lang: "Kalaallisut", region: "Greenland" },
   kl: { lang: "Kalaallisut" },
   kln_KE: { lang: "Kalenjin", region: "Kenya" },
   kln: { lang: "Kalenjin" },
   kam_KE: { lang: "Kamba", region: "Kenya" },
   kam: { lang: "Kamba" },
   kn_IN: { lang: "Kannada", region: "India" },
   kn: { lang: "Kannada" },
   kk_Cyrl: { lang: "Kazakh", region: "Cyrillic" },
   kk_Cyrl_KZ: { lang: "Kazakh", region: "Cyrillic, Kazakhstan" },
   kk: { lang: "Kazakh" },
   km_KH: { lang: "Khmer", region: "Cambodia" },
   km: { lang: "Khmer" },
   ki_KE: { lang: "Kikuyu", region: "Kenya" },
   ki: { lang: "Kikuyu" },
   rw_RW: { lang: "Kinyarwanda", region: "Rwanda" },
   rw: { lang: "Kinyarwanda" },
   kok_IN: { lang: "Konkani", region: "India" },
   kok: { lang: "Konkani" },
   ko_KR: { lang: "Korean", region: "South Korea" },
   ko: { lang: "Korean" },
   khq_ML: { lang: "Koyra Chiini", region: "Mali" },
   khq: { lang: "Koyra Chiini" },
   ses_ML: { lang: "Koyraboro Senni", region: "Mali" },
   ses: { lang: "Koyraboro Senni" },
   lag_TZ: { lang: "Langi", region: "Tanzania" },
   lag: { lang: "Langi" },
   lv_LV: { lang: "Latvian", region: "Latvia" },
   lv: { lang: "Latvian" },
   lt_LT: { lang: "Lithuanian", region: "Lithuania" },
   lt: { lang: "Lithuanian" },
   luo_KE: { lang: "Luo", region: "Kenya" },
   luo: { lang: "Luo" },
   luy_KE: { lang: "Luyia", region: "Kenya" },
   luy: { lang: "Luyia" },
   mk_MK: { lang: "Macedonian", region: "Macedonia" },
   mk: { lang: "Macedonian" },
   jmc_TZ: { lang: "Machame", region: "Tanzania" },
   jmc: { lang: "Machame" },
   kde_TZ: { lang: "Makonde", region: "Tanzania" },
   kde: { lang: "Makonde" },
   mg_MG: { lang: "Malagasy", region: "Madagascar" },
   mg: { lang: "Malagasy" },
   ms_BN: { lang: "Malay", region: "Brunei" },
   ms_MY: { lang: "Malay", region: "Malaysia" },
   ms: { lang: "Malay" },
   ml_IN: { lang: "Malayalam", region: "India" },
   ml: { lang: "Malayalam" },
   mt_MT: { lang: "Maltese", region: "Malta" },
   mt: { lang: "Maltese" },
   gv_GB: { lang: "Manx", region: "United Kingdom" },
   gv: { lang: "Manx" },
   mr_IN: { lang: "Marathi", region: "India" },
   mr: { lang: "Marathi" },
   mas_KE: { lang: "Masai", region: "Kenya" },
   mas_TZ: { lang: "Masai", region: "Tanzania" },
   mas: { lang: "Masai" },
   mer_KE: { lang: "Meru", region: "Kenya" },
   mer: { lang: "Meru" },
   mfe_MU: { lang: "Morisyen", region: "Mauritius" },
   mfe: { lang: "Morisyen" },
   naq_NA: { lang: "Nama", region: "Namibia" },
   naq: { lang: "Nama" },
   ne_IN: { lang: "Nepali", region: "India" },
   ne_NP: { lang: "Nepali", region: "Nepal" },
   ne: { lang: "Nepali" },
   nd_ZW: { lang: "North Ndebele", region: "Zimbabwe" },
   nd: { lang: "North Ndebele" },
   nb_NO: { lang: "Norwegian Bokmål", region: "Norway" },
   nb: { lang: "Norwegian Bokmål" },
   nn_NO: { lang: "Norwegian Nynorsk", region: "Norway" },
   nn: { lang: "Norwegian Nynorsk" },
   nyn_UG: { lang: "Nyankole", region: "Uganda" },
   nyn: { lang: "Nyankole" },
   or_IN: { lang: "Oriya", region: "India" },
   or: { lang: "Oriya" },
   om_ET: { lang: "Oromo", region: "Ethiopia" },
   om_KE: { lang: "Oromo", region: "Kenya" },
   om: { lang: "Oromo" },
   ps_AF: { lang: "Pashto", region: "Afghanistan" },
   ps: { lang: "Pashto" },
   fa_AF: { lang: "Persian", region: "Afghanistan" },
   fa_IR: { lang: "Persian", region: "Iran" },
   fa: { lang: "Persian" },
   pl_PL: { lang: "Polish", region: "Poland" },
   pl: { lang: "Polish" },
   pt_BR: { lang: "Portuguese", region: "Brazil" },
   pt_GW: { lang: "Portuguese", region: "Guinea-Bissau" },
   pt_MZ: { lang: "Portuguese", region: "Mozambique" },
   pt_PT: { lang: "Portuguese", region: "Portugal" },
   pt: { lang: "Portuguese" },
   pa_Arab: { lang: "Punjabi", region: "Arabic" },
   pa_Arab_PK: { lang: "Punjabi", region: "Arabic, Pakistan" },
   pa_Guru: { lang: "Punjabi", region: "Gurmukhi" },
   pa_Guru_IN: { lang: "Punjabi", region: "Gurmukhi, India" },
   pa: { lang: "Punjabi" },
   ro_MD: { lang: "Romanian", region: "Moldova" },
   ro_RO: { lang: "Romanian", region: "Romania" },
   ro: { lang: "Romanian" },
   rm_CH: { lang: "Romansh", region: "Switzerland" },
   rm: { lang: "Romansh" },
   rof_TZ: { lang: "Rombo", region: "Tanzania" },
   rof: { lang: "Rombo" },
   ru_MD: { lang: "Russian", region: "Moldova" },
   ru_RU: { lang: "Russian", region: "Russia" },
   ru_UA: { lang: "Russian", region: "Ukraine" },
   ru: { lang: "Russian" },
   rwk_TZ: { lang: "Rwa", region: "Tanzania" },
   rwk: { lang: "Rwa" },
   saq_KE: { lang: "Samburu", region: "Kenya" },
   saq: { lang: "Samburu" },
   sg_CF: { lang: "Sango", region: "Central African Republic" },
   sg: { lang: "Sango" },
   seh_MZ: { lang: "Sena", region: "Mozambique" },
   seh: { lang: "Sena" },
   sr_Cyrl: { lang: "Serbian", region: "Cyrillic" },
   sr_Cyrl_BA: { lang: "Serbian", region: "Cyrillic, Bosnia and Herzegovina" },
   sr_Cyrl_ME: { lang: "Serbian", region: "Cyrillic, Montenegro" },
   sr_Cyrl_RS: { lang: "Serbian", region: "Cyrillic, Serbia" },
   sr_Latn: { lang: "Serbian", region: "Latin" },
   sr_Latn_BA: { lang: "Serbian", region: "Latin, Bosnia and Herzegovina" },
   sr_Latn_ME: { lang: "Serbian", region: "Latin, Montenegro" },
   sr_Latn_RS: { lang: "Serbian", region: "Latin, Serbia" },
   sr: { lang: "Serbian" },
   sn_ZW: { lang: "Shona", region: "Zimbabwe" },
   sn: { lang: "Shona" },
   ii_CN: { lang: "Sichuan Yi", region: "China" },
   ii: { lang: "Sichuan Yi" },
   si_LK: { lang: "Sinhala", region: "Sri Lanka" },
   si: { lang: "Sinhala" },
   sk_SK: { lang: "Slovak", region: "Slovakia" },
   sk: { lang: "Slovak" },
   sl_SI: { lang: "Slovenian", region: "Slovenia" },
   sl: { lang: "Slovenian" },
   xog_UG: { lang: "Soga", region: "Uganda" },
   xog: { lang: "Soga" },
   so_DJ: { lang: "Somali", region: "Djibouti" },
   so_ET: { lang: "Somali", region: "Ethiopia" },
   so_KE: { lang: "Somali", region: "Kenya" },
   so_SO: { lang: "Somali", region: "Somalia" },
   so: { lang: "Somali" },
   es_AR: { lang: "Spanish", region: "Argentina" },
   es_BO: { lang: "Spanish", region: "Bolivia" },
   es_CL: { lang: "Spanish", region: "Chile" },
   es_CO: { lang: "Spanish", region: "Colombia" },
   es_CR: { lang: "Spanish", region: "Costa Rica" },
   es_DO: { lang: "Spanish", region: "Dominican Republic" },
   es_EC: { lang: "Spanish", region: "Ecuador" },
   es_SV: { lang: "Spanish", region: "El Salvador" },
   es_GQ: { lang: "Spanish", region: "Equatorial Guinea" },
   es_GT: { lang: "Spanish", region: "Guatemala" },
   es_HN: { lang: "Spanish", region: "Honduras" },
   es_419: { lang: "Spanish", region: "Latin America" },
   es_MX: { lang: "Spanish", region: "Mexico" },
   es_NI: { lang: "Spanish", region: "Nicaragua" },
   es_PA: { lang: "Spanish", region: "Panama" },
   es_PY: { lang: "Spanish", region: "Paraguay" },
   es_PE: { lang: "Spanish", region: "Peru" },
   es_PR: { lang: "Spanish", region: "Puerto Rico" },
   es_ES: { lang: "Spanish", region: "Spain" },
   es_US: { lang: "Spanish", region: "United States" },
   es_UY: { lang: "Spanish", region: "Uruguay" },
   es_VE: { lang: "Spanish", region: "Venezuela" },
   es: { lang: "Spanish" },
   sw_KE: { lang: "Swahili", region: "Kenya" },
   sw_TZ: { lang: "Swahili", region: "Tanzania" },
   sw: { lang: "Swahili" },
   sv_FI: { lang: "Swedish", region: "Finland" },
   sv_SE: { lang: "Swedish", region: "Sweden" },
   sv: { lang: "Swedish" },
   gsw_CH: { lang: "Swiss German", region: "Switzerland" },
   gsw: { lang: "Swiss German" },
   shi_Latn: { lang: "Tachelhit", region: "Latin" },
   shi_Latn_MA: { lang: "Tachelhit", region: "Latin, Morocco" },
   shi_Tfng: { lang: "Tachelhit", region: "Tifinagh" },
   shi_Tfng_MA: { lang: "Tachelhit", region: "Tifinagh, Morocco" },
   shi: { lang: "Tachelhit" },
   dav_KE: { lang: "Taita", region: "Kenya" },
   dav: { lang: "Taita" },
   ta_IN: { lang: "Tamil", region: "India" },
   ta_LK: { lang: "Tamil", region: "Sri Lanka" },
   ta: { lang: "Tamil" },
   te_IN: { lang: "Telugu", region: "India" },
   te: { lang: "Telugu" },
   teo_KE: { lang: "Teso", region: "Kenya" },
   teo_UG: { lang: "Teso", region: "Uganda" },
   teo: { lang: "Teso" },
   th_TH: { lang: "Thai", region: "Thailand" },
   th: { lang: "Thai" },
   bo_CN: { lang: "Tibetan", region: "China" },
   bo_IN: { lang: "Tibetan", region: "India" },
   bo: { lang: "Tibetan" },
   ti_ER: { lang: "Tigrinya", region: "Eritrea" },
   ti_ET: { lang: "Tigrinya", region: "Ethiopia" },
   ti: { lang: "Tigrinya" },
   to_TO: { lang: "Tonga", region: "Tonga" },
   to: { lang: "Tonga" },
   tr_TR: { lang: "Turkish", region: "Turkey" },
   tr: { lang: "Turkish" },
   uk_UA: { lang: "Ukrainian", region: "Ukraine" },
   uk: { lang: "Ukrainian" },
   ur_IN: { lang: "Urdu", region: "India" },
   ur_PK: { lang: "Urdu", region: "Pakistan" },
   ur: { lang: "Urdu" },
   uz_Arab: { lang: "Uzbek", region: "Arabic" },
   uz_Arab_AF: { lang: "Uzbek", region: "Arabic, Afghanistan" },
   uz_Cyrl: { lang: "Uzbek", region: "Cyrillic" },
   uz_Cyrl_UZ: { lang: "Uzbek", region: "Cyrillic, Uzbekistan" },
   uz_Latn: { lang: "Uzbek", region: "Latin" },
   uz_Latn_UZ: { lang: "Uzbek", region: "Latin, Uzbekistan" },
   uz: { lang: "Uzbek" },
   vi_VN: { lang: "Vietnamese", region: "Vietnam" },
   vi: { lang: "Vietnamese" },
   vun_TZ: { lang: "Vunjo", region: "Tanzania" },
   vun: { lang: "Vunjo" },
   cy_GB: { lang: "Welsh", region: "United Kingdom" },
   cy: { lang: "Welsh" },
   yo_NG: { lang: "Yoruba", region: "Nigeria" },
   yo: { lang: "Yoruba" },
   zu_ZA: { lang: "Zulu", region: "South Africa" },
   zu: { lang: "Zulu" }
}